define([
    "./ui",
    "./Widget",
    "./Accordion",
    "./Button",
    "./Carousel",
    "./Checkbox",
    "./Combobox",
    "./Menu",
    "./Pagination",
    "./Progress",
    "./Radio",
    "./TabStrip",
    "./Textbox",
    "./Toolbar"
/*    
    "./checkbox",
    "./combobox",
    "./datepicker",
    "./dropdown-autoflip",
    "./infinite-scroll",
    "./loader",
    "./menu",
    "./picker",
    "./pillbox",
    "./placard",
    "./radio",
    "./scheduler",
    "./search",
    "./selectlist",
    "./spinbox",
    "./toolbar",
    "./wizard"
*/
], function(ui) {
    return ui;
});